### ISSUE TITLE
Will not open BT properties on latest joying FW.

### ISSUE THREAD

**Issue by wishbone1138** [lbdroid/JoyingIntelStuff#3]
Application will not open BT properties on my Joying. It tries to open and then closes returning to the app.  I'm running 6.0.1 may 25.

**Comment by lbdroid** [comment]
Yep. The bastards deleted the proper bluetooth settings starting with 6.0. There is nothing I can do about it. What *you* can do, is extract and install the original settings app from the update package. There are instructions somewhere in joying forum to do that if you look hard enough.

**Comment by wishbone1138** [comment]
Yeah that's what I figured, thanks for the heads up, I'll look for it.
